[#1] 프로젝트 생성 및 설명
thenaun-workspace/covid-19-info pull request #2
Opened 2020-12-13 22:14 UTC by Hyung1Jung

2020-12-14 11:43 UTC, thenaun-woody requested changes
아직 feature가 없는 상태라 간단하게만 남겼어요~

2020-12-14 11:43 UTC, thenaun-woody commented on covid19-api/build.gradle
> +/*
build.gradle에 이렇게 주석을 달아놓은 이유는 뭔가요?
이런것들은 그냥 wiki나 README 추가사항으로 정리해주세요.

하단의 gradle에 대한 설명이니, lombok에 대한 설명이니 누구나 다 아는내용이고 dependency가 추가될 때 마다 여기 주석에 정리할건 아닌거같아요

2020-12-14 11:43 UTC, thenaun-woody commented on covid19-api/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
일단은 api 호출형태로 서빙할 것이기 때문에 지금 jpa 관련 의존성은 제거하는게 좋을것 같네요. 추후에 사용을 할 때 넣는 것으로 하죠

2020-12-14 11:43 UTC, thenaun-woody commented on covid19-api/build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
mysql 도 위와 마찬가지로요 :) 
지금은 간단하게 h2로 가도 될거같아요.

2020-12-14 11:43 UTC, thenaun-woody commented on covid19-api/build.gradle
> +        exclude module: 'junit'
starter에 포함이 되는데 exclude 하고 밑에 5.2버전을 따로 명시를 하신 이유가 있을까요?

2020-12-14 11:43 UTC, thenaun-woody commented on settings.gradle
> +        gradlePluginPortal()
이거는 어떤것 때문에 추가하신걸까요?

2020-12-14 11:43 UTC, thenaun-woody commented on settings.gradle
> +include 'covid19-api'
👍

2020-12-14 13:41 UTC, Hyung1Jung commented on covid19-api/build.gradle
> +/*
녜! 수정하겠습니다! 추 후 wiki와 README를 정리할 때 추가사항으로 정리하겠습니다.

2020-12-14 13:41 UTC, Hyung1Jung commented on covid19-api/build.gradle
> +    runtimeOnly 'mysql:mysql-connector-java'
네 JPA와 mysql 의존성 우선 삭제하고 h2로 가겠습니다!

2020-12-14 19:49 UTC, Hyung1Jung commented
d

2020-12-14 19:57 UTC, Hyung1Jung commented
수정하였습니다!

2020-12-15 03:38 UTC, thenaun-woody commented
> 우선 5개의 모듈로 나누고, 또 말씀해주신 것을 반영하여 리팩토링 해보았습니다!

기능이 우선 api 호출로 서빙하는 기능이 하나인데, 너무 많이 나눠진거같아요. 기능이 추가되고 역할이 나눠져야할때 나누는게 좋을거같습니다.
저희가 구조에 대해서 이야기 나누었던 부분은 완전 최종적인 그림이고요. 지금은 처음에 올려주신 api 하나로 충분할것같습니다.

2020-12-15 03:42 UTC, thenaun-woody commented
module만 일단은 첫번째 feature만 담당하는 api 서버 하나로 두고 시작을 하는게 좋을것 같습니다~
네이밍도 형일님께서 open-api를 가공하여 제공하는 서버기 때문에 모듈이름도 open을 제외하는게 좋을것 같아요.
모듈이 정리되면 merge해주세요~

2020-12-15 03:43 UTC, thenaun-woody commented
여기 README는 웹에서 만드신것과 프로젝트에서 직접 만드신것과 달라서 충돌이 나는것 같네요. 하나를 선택해서 정리해주시면 될것 같아요~

2020-12-15 10:49 UTC, Hyung1Jung commented
제가 뭘 잘못만졌는지..reply 달 때 자꾸 pending로 들어오네요..
첫번째 feature는 api 서버 하나로 두고 시작하도록 하겠습니다! 네이밍도 open을 제외하도록 하겠습니다. 
추가로 README 하나는 정리 한 후 merge하도록 하겠습니다!
@thenaun-woody

2020-12-15 15:02 UTC, merged