[#2] open api get raw data
thenaun-workspace/covid-19-info pull request #4
Opened 2020-12-19 12:42 UTC by Hyung1Jung

2020-12-19 16:05 UTC, Hyung1Jung commented
feature2에 데이터 받아오는 작업만 했었어야  했는데 제가 한 번에 feature2에 다하려고 했나 싶은 생각이 듭니다..
데이터만 받아오는 것을 feature2로 두고 머지 후
HttpComponentsClientHttpRequestFactory 관련 customize을 feature3으로 하고 exception을 feature4로 했을 걸 싶네요.

또, HttpComponentsClientHttpRequestFactory 관련 customize을 config 패키지를 하나 만들어 refactoring하려고 생각중입니다!

2020-12-20 00:03 UTC, thenaun-woody requested changes
open-api 에서 받아오는 데이터를 raw 데이터로 의미를 두신거같아요. 앞단에 serving할때 가공이 전혀 되고 있지 않습니다. 
클라이언트가 어떤 api가 필요할지 기획에 정리를 하셨던거같아요. 해당 api중 대표적인 것 하나를 먼저 구현해봤으면 좋겠다고했는데, 그 부분 하나를 먼저 진행을 하시면 더 나을 것 같습니다 :)

그리고 layer가 잘 나눠지지 않은것 같고 테스트코드가 필요합니다. 자세한 내용은 직접 피드백 드릴게요.

2020-12-20 00:03 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/service/RawDataService.java
> +        Object response = restTemplate.getForObject(uri.toUriString(), String.class);
response를 String으로 받아오셨네요. open-api에서 제공해주시는 데이터가 어떤 형태이고 어떻게 받아올지 고민을 다시 해보시면 좋을 것 같습니다.
`jackson` 관련해서 보시면 필드 매핑이 더 쉬워질거에요.
또한 restTemplate의 `exchange` 메서드도 한 번 보시면 좋을 것 같습니다.

2020-12-20 00:17 UTC, Hyung1Jung commented
네! 리뷰 다 확인하였습니다. 말씀해주신 것들대로 리팩토링 진행하도록 해보겠습니다.
@thenaun-woody :)

2020-12-20 00:27 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/service/RawDataService.java
> +        CloseableHttpClient httpClient = HttpClientBuilder.create()
maxConnTotal은 연결을 유지할 최대 숫자, maxConnPerRoute는 특정 경로당 최대 숫자로 설정을 해두었는데 괄호 안에 숫자는 어떻게 넣어야 할지 아직 잘 모르겠어서 임의로 넣어놨습니다.
서버에 요청이 많을 때, Thread가 급격히 증가하는 문제에 관하여 connetion 수를 제한하기 위해 설정 해두었습니다!

2020-12-20 00:36 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/service/RawDataService.java
> +        factory.setReadTimeout(5000);
사용자가 연결에 문제가 있을시, 시간 제한을 두고 커넥션 풀에서 빠져나오게 하려고 설정해놓았습니다.

2020-12-22 10:12 UTC, Hyung1Jung commented
현재 dto에서 @JsonProperty을 이용하여 mapping 해주고 data를 찔러보았는데 계속 0 or null만 들어와서,
공부 계속해보며 고민, 리팩토링 중입니다.
우선 현재 상황까지 pr 보냅니당..
@thenaun-woody

2020-12-22 13:14 UTC, thenaun-woody requested changes
고생많으셨어요~ 🙏
이번 주에 저랑 짧게라도 페어 프로그래밍 한 번 하는건 어떨까요?
전체적인 구조 부터 디테일 한 부분까지 같이 이야기 나눠보아요 :)
[IntelliJ Pair Programming](https://plugins.jetbrains.com/plugin/14896-code-with-me)

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/controller/dto/ItemDto.java
> +    public int id;              // 감염현황 고유 값(게시글 번호)
제가 open-api 문서를 좀 확인해보았는데요.
외부데이터는 언제 어떻게 바뀔지 모릅니다. 특히나 open-api 같은 경우는 데이터가 엉망으로 내려오는 경우가 종종 있어요.
그렇기 때문에 거기에 의존한 id는 매우 위험합니다. seq로 적재는 하되 키로잡지는 마세요. (물론 여기는 dto라 엔티티 key에서 쓰실지 아닐지는 모르겠지만 왠지 그럴거같아서 말씀드립니다)

오히려 이런 api는 눈으로 식별하려면 날짜와 데이터가 밀어넣어진 시간을 비교하면서 확인하는게 좋습니다.

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/controller/dto/ItemDto.java
> +    @JsonProperty("updateDt")
제가 open-api를 수 회 찔러보았는데요.
특정일은 해당 필드가 null로 내려오고 특정일은 날짜가 박혀있는 형태로 내려옵니다.

💡 이거는 데이터가 어떤 형태로 밀어넣어지고 있을까요?

이 패턴에 따라 서버에서 데이터 보정작업을 어떻게 해야될지가 결정이 되겠죠?

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/controller/dto/ItemDto.java
> +/*
사용하지 않는 주석은 지워주세요 :) 

그리고 엔티티의 id를 seq로 세팅하고있네요. 밑에 보면 `IDENTITY` 전략을 쓰고있는데요. 서로 충돌이 나는거같네요.

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/domain/entity/Body.java
> +public class Body {
Body와 Header는 무슨 엔티티인가요?

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/domain/entity/Item.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
위에서 언급드린 부분입니다.

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/domain/entity/Item.java
> +@Setter
엔티티에 Setter가 필요할까요?

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/domain/entity/Item.java
> +    public String updateDate;    // 수정일시분초
날짜도 String으로 관리하시는 이유가 있을까요?

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/domain/entity/Item.java
> +public class Item {
네이밍도 수업 때 같이 고민해보아요 :)

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/exception/RestTemplateResponseErrorHandler.java
> +public class RestTemplateResponseErrorHandler extends DefaultResponseErrorHandler {
커스텀 로그만 남기려고 재정의하신건가요?

2020-12-22 13:14 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/service/TodayDataService.java
> +    private final UriComponents uri;
위에 config 패키지에서 말씀드린 부분입니다.

2020-12-22 19:57 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/controller/TodayDataController.java
> +public class TodayDataController {
네네 오늘자만 서빙해주는 컨트롤러여서 우선 이렇게 네이밍하였습니다! 던일 대비, 혹은 특정 날짜에 대한 데이터는 다른 컨트롤러를 쓰려고 했습니다!

2020-12-22 19:58 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/controller/TodayDataController.java
> +    @GetMapping("/api/today/confirm/info")
네네 오늘 날짜의 확진자수를 가져올라교 했습니다! 전일자나 특정일자에 관한 데이터는 파라미터로 받아오려고 하였습니다!

2020-12-22 20:00 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/domain/entity/Item.java
> +@Setter
삭제하겠습니다! 혼자 이런 저런 코드 학습을 해보면서 잠시 붙여두었다가 지우지 않았던 것 같습니다!

2020-12-22 20:02 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/domain/entity/Item.java
> +    public String updateDate;    // 수정일시분초
앗 저건 아직 리팩토링을 하지 않아서 데이터 들어오나 확인만 하기 위해 잠시 String으로 해놨는데 리팩토링 해보도록 하겠습니다! 원래는 Date로 받을 생각을 하고 있엇습니다!

2020-12-22 20:02 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/domain/entity/Item.java
> +public class Item {
네!

2020-12-22 20:03 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/exception/RestTemplateResponseErrorHandler.java
> +public class RestTemplateResponseErrorHandler extends DefaultResponseErrorHandler {
네! 그럤었습니다!

2020-12-22 20:03 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/service/TodayDataService.java
> +    private final UriComponents uri;
네네 이것에 관해 더 고민해보겠습니다!

2020-12-22 20:04 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/config/RestTemplateConfig.java
> +    HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory();
메서드마다 붙여주면 호출할때마다 힙 메모리 낭비할까봐 올려놨습니다!

2020-12-22 20:06 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/config/RestTemplateConfig.java
> +    public UriComponents uri() {
아 네네 생각해보니 관과하고 있었던 부분이네요.. 그럴때마다 Bean 재정의하는건 효율적이지 않을 것 같네요.. 더 효율적인 코드로 고민해보겠습니다

2020-12-22 20:09 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/controller/dto/ItemDto.java
> +    public int id;              // 감염현황 고유 값(게시글 번호)
아 네네 감사합니다! open api 문서에서 seq를를 고유값으로 명시해놨길레 그것을 보고 key로 생각했던 것 같습니다.  말씀해주신대로 고민해보곘습니다!

2020-12-22 20:09 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/controller/dto/ItemDto.java
> +/*
네 알겠습니다!

2020-12-22 20:10 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/controller/dto/ItemDto.java
> +    @JsonProperty("updateDt")
네네 보정작업에 관해 고민해보겠습니다!

2020-12-22 20:12 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/domain/entity/Body.java
> +public class Body {
body는 결과 코드와 메시지,  Body는 게시물의 페이지수, 페이지 수당 몇개를 보여줄껀지, 시작~종료 날짜를 위해 만들어 놓았는데 현재는 필요없는 것 같아 우선 없애도록 하겠습니다!

2020-12-23 06:17 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/config/RestTemplateConfig.java
> +    HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory();
페어프로그래밍 너무 좋습니다!  행아웃 전에 미리 준비해놓도록 하겠습니다 :)

2020-12-26 12:26 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/config/RestTemplateConfig.java
> +    HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory();
저 factory를 RestTemplate Bean을 정의할 때 사용하고있어서 언급드렸어요~

2020-12-26 12:27 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/controller/TodayDataController.java
> +public class TodayDataController {
그럼 api 하나당 컨트롤러가 하나씩 만들어지는건가요? 너무 복잡하지 않을까요?

2020-12-26 12:34 UTC, thenaun-woody commented on covid19-api/src/main/java/com/covid19/exception/RestTemplateResponseErrorHandler.java
> +public class RestTemplateResponseErrorHandler extends DefaultResponseErrorHandler {
hasError나 handleError나 둘다 똑같은 로그를 찍고 있어요.
두 가지 메서드의 역할을 보셨을까요?
에러핸들러를 재정의하는 것은 어떤걸 error상황으로 볼건지, error 핸들링을 상태코드에 따라서 달리할건지에 따른 재정의를 하는데 주로 쓰입니다.
현재는 그만한 분기를 탈 정도로 보이지 않습니다.

open-api의 스펙을 다시 한번 살펴보시고 어떤 상태가 내려오느냐에 따른 기획이 정해져야 할 문제로 보이네요. 문서에서 찾아보시고 정리해보시고 각각의 응답을 애플리케이션에서 어떤 상황으로 볼지 스스로 정의해보세요.

2020-12-26 12:43 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/exception/RestTemplateResponseErrorHandler.java
> +public class RestTemplateResponseErrorHandler extends DefaultResponseErrorHandler {
네! 메서드의 역할은 확인하였습니다. 2xx상태코드 이외에 상황에 따라 적용되는 것으로 파악하고 구현을 하였었는데, 짜놓고도 아직 그만한 분기를 탈 정도는 아니라고 생각이 들었습니다. DefaultResponseErrorHandler를 상속받는게 if ~else를 써서 예외처리하는 것 보다 더 효울적이라고 판단하여 썼엇는데 아직은 분기 탈 정도가 아니라 생각하여 말씀해주신대로 고민해보겠습니다.

2020-12-26 12:45 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/controller/TodayDataController.java
> +public class TodayDataController {
네! 저도 지금은 그렇게 생각하여 특정 날짜만 get(@PathVariable String stateDate) 형식으로 받아 조회하려고 생각중입니다.

2020-12-26 12:53 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/config/RestTemplateConfig.java
> +    HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory();
현재는 메서드 안에 넣어놨습니다! 위로 인스턴스 변수로 올리면 Bean 사용 목적에 적합하지 않아서 메서드 안으로 넣어놨습니다!

2020-12-26 12:59 UTC, Hyung1Jung commented on covid19-api/src/main/java/com/covid19/config/RestTemplateConfig.java
> +    HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory();
또한 TimeOut관련해서 설정 값을 yml으로 옮겨 프로퍼티 주입 방식으로 리팩토링 할 예정입니다.

2020-12-31 10:08 UTC, Hyung1Jung commented
전체적으로 코드 리팩토링을 더 많이 해야 될 것 같고, domain-caller-Components, Json 파일을 enum을 좀 더 공부한 후 bean 등록 해제하고 eunm 클래스로 리팩토링 할 예정입니다. 또, 일일확진자 api에서 ~12.30일까지의 일일확진자는 나오지만, 12월 31일, 오늘 당일의 확진자는 아직 데이터가 내려오지 않는 것에 관한 처리, 그 외 여러 처리에 관해는 좀 더 생각해 보아야 할 것 같습니다.
아직 고민하고 리팩토링할게 많지만, 우선 pr 한 번 보냈습니다~
@thenaun-woody

2020-12-31 10:13 UTC, Hyung1Jung commented
전체적으로 코드 리팩토링을 더 많이 해야 될 것 같고, domain-caller-Components, Json 파일을 enum을 좀 더 공부한 후 bean 등록 해제하고 eunm 클래스로 리팩토링 할 예정입니다. 또, 일일확진자 api에서 ~12.30일까지의 일일확진자는 나오지만, 12월 31일, 오늘 당일의 확진자는 아직 데이터가 내려오지 않는 것에 관한 처리, 그 외 여러 처리에 관해는 좀 더 생각해 보아야 할 것 같습니다.
아직 고민하고 리팩토링할게 많지만, 우선 pr 한 번 보냈습니다~
@thenaun-woody

2021-01-01 07:30 UTC, thenaun-woody approved these changes
음 이번 피쳐가 아닌 내용들 (repository save)이 들어가있네요.
한번에 너무 많은 걸 하려고하다보니 그런것으로보여요. 리뷰드릴게 많은데 이 상황에서 리뷰를 드리면 더 오래걸릴거같아요. 그래서 지금상황에서 리뷰를 남기지 않았어요.
피쳐가 너무 길어지고있어 일단 merge하도록할게요.
merge이후에 issue를 하나씩 따서 작은부분부터 고쳐나가는게 좋을 것 같습니다 :)

2021-01-01 17:39 UTC, merged